// Fixed products for SME Division
export const smeProducts = {
  smeRestructuringLoans: {
    name: 'SME Restructuring Loans',
    productType: 'Credit',
    type: 'french',
    durata: 20,
    gracePeriod: 0,
    volumeArray: [40, 100, 160, 240, 320, 320, 320, 320, 320, 320],
    spread: 4.5,
    rwaDensity: 85,
    dangerRate: 3.0,
    lgd: 45,
    ltv: 60,
    recoveryCosts: 12,
    collateralHaircut: 30,
    avgLoanSize: 0.8,
    creditClassification: 'Bonis',
    isFixedRate: false,
    commissionRate: 1.5,
    equityUpside: 0,
    ftpRate: 1.5,
    isSecured: true,
    hasStateGuarantee: 'MCC'
  },
  smeWorkingCapital: {
    name: 'Working Capital Lines',
    productType: 'Credit',
    type: 'bullet',
    durata: 4,
    gracePeriod: 0,
    volumeArray: [30, 75, 120, 180, 240, 240, 240, 240, 240, 240],
    spread: 3.5,
    rwaDensity: 75,
    dangerRate: 2.5,
    lgd: 40,
    ltv: 0,
    recoveryCosts: 10,
    collateralHaircut: 0,
    avgLoanSize: 0.3,
    creditClassification: 'Bonis',
    isFixedRate: false,
    commissionRate: 0.5,
    equityUpside: 0,
    ftpRate: 1.5,
    isSecured: false,
    unsecuredLGD: 45,
    hasStateGuarantee: 'Not Present'
  },
  smeGrowthLoans: {
    name: 'SME Growth Financing',
    productType: 'Credit',
    type: 'french',
    durata: 28,
    gracePeriod: 8,
    volumeArray: [20, 50, 80, 120, 160, 200, 200, 200, 200, 200],
    spread: 3.8,
    rwaDensity: 70,
    dangerRate: 2.0,
    lgd: 40,
    ltv: 65,
    recoveryCosts: 10,
    collateralHaircut: 25,
    avgLoanSize: 1.2,
    creditClassification: 'Bonis',
    isFixedRate: false,
    commissionRate: 1.0,
    equityUpside: 0,
    ftpRate: 1.5,
    isSecured: true,
    hasStateGuarantee: 'SACE'
  }
};