// Fixed products for Real Estate Division
export const realEstateProducts = {
  reBridgeLoans: {
    name: 'Bridge Loans Real Estate',
    division: 'RealEstateFinancing',
    productType: 'Credit',
    type: 'bullet',
    durata: 8,
    gracePeriod: 0,
    volumeArray: [50, 125, 200, 300, 400, 400, 400, 400, 400, 400],
    spread: 3.5,
    rwaDensity: 65,
    dangerRate: 2.0,
    lgd: 35,
    ltv: 70,
    recoveryCosts: 8,
    collateralHaircut: 20,
    avgLoanSize: 2.5,
    creditClassification: 'Bonis',
    isFixedRate: false,
    commissionRate: 0.75,
    equityUpside: 0,
    ftpRate: 1.5,
    isSecured: true,
    hasStateGuarantee: 'Not Present'
  },
  reDevelopmentLoans: {
    name: 'Development Loans',
    division: 'RealEstateFinancing',
    productType: 'Credit',
    type: 'french',
    durata: 20,
    gracePeriod: 0,
    volumeArray: [30, 75, 120, 180, 240, 300, 300, 300, 300, 300],
    spread: 4.0,
    rwaDensity: 75,
    dangerRate: 2.5,
    lgd: 40,
    ltv: 65,
    recoveryCosts: 10,
    collateralHaircut: 25,
    avgLoanSize: 5.0,
    creditClassification: 'Bonis',
    isFixedRate: false,
    commissionRate: 1.0,
    equityUpside: 0,
    ftpRate: 1.5,
    isSecured: true,
    hasStateGuarantee: 'Not Present'
  },
  reAcquisitionLoans: {
    name: 'Acquisition Financing',
    division: 'RealEstateFinancing',
    productType: 'Credit',
    type: 'french',
    durata: 28,
    gracePeriod: 8,
    volumeArray: [40, 100, 160, 240, 320, 400, 400, 400, 400, 400],
    spread: 3.0,
    rwaDensity: 60,
    dangerRate: 1.5,
    lgd: 35,
    ltv: 75,
    recoveryCosts: 8,
    collateralHaircut: 15,
    avgLoanSize: 3.0,
    creditClassification: 'Bonis',
    isFixedRate: false,
    commissionRate: 0.5,
    equityUpside: 0,
    ftpRate: 1.5,
    isSecured: true,
    hasStateGuarantee: 'Not Present'
  }
};